### Localhost testing
GET http://localhost:3000/items

###

POST http://localhost:3000/items
Content-Type: application/json

{
    "name": "Testing 3"
}

### QA testing
GET http://3.84.142.186:3000/items

POST http://3.84.142.186:3000/items
Content-Type: application/json

{
    "name": "Testing 3"
}

### Staging testing
GET http://54.89.147.251:3000/items

###
POST http://54.89.147.251:3000/items
Content-Type: application/json

{
    "name": "Testing 3"
}